ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]


:toc:
:toc-placement!:

= Mobile Security Service Operator

ifdef::status[]
.*Project health*
image:https://img.shields.io/:license-Apache2-blue.svg[License (License), link=http://www.apache.org/licenses/LICENSE-2.0]
image:https://goreportcard.com/badge/github.com/aerogear/mobile-security-service-operator[Go Report Card (Go Report Card), link=https://goreportcard.com/report/github.com/aerogear/mobile-security-service-operator]
endif::[]

:toc:
toc::[]

== Overview

A https://commons.openshift.org/sig/OpenshiftOperators.html[Operator] based on the https://github.com/operator-framework/operator-sdk[Operator SDK] that installs and maintains https://github.com/aerogear/mobile-security-service[AeroGear Mobile Security Service] on a cluster.

NOTE: This project is a POC

== Prerequisites

|===
|https://golang.org/doc/install[Install Golang]
|https://github.com/golang/go/wiki/SettingGOPATH[Ensure the $GOPATH environment variable is set]
|https://golang.github.io/dep/docs/installation.html[Install the dep package manager]
|https://github.com/operator-framework/operator-sdk#quick-start[Install Operator-SDK]
|https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl[Install kubectl]
|===

== Getting Started

=== To run on Minishift
https://docs.okd.io/latest/minishift/getting-started/installing.html[Install Minishift] then enable Operators on it by running the following commands.

[source,shell]
----
# create a new profile to test the operator
$ minishift profile set operator

# enable the admin-user add-on
$ minishift addon enable admin-user

# start the instance
$ minishift start
----

=== To install Mobile Security Service Operator in cluster

==== Login as system:admin

To install the operator is required have admin permissions in the cluster.

[source,shell]
----
$ oc login -u system:admin
----

NOTE: This operator will be installed in the cluster level.

==== To deploy Mobile Security Service Operator

Run the following commands to deploy the operator in your cluster.

[source,shell]
----
$ kubectl create namespace mobile-security-service
$ kubectl create -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml
$ kubectl create -f deploy/cluster_role.yaml
$ kubectl create -f deploy/cluster_role_binding.yaml
$ kubectl create -f deploy/service_account.yaml
$ kubectl create -f deploy/operator.yaml
----

NOTE: You can use `oc` tools instead of `kubectl`. E.g. (`$ oc create namespace mobile-security-service`)

=== To deploy Mobile Security Service in a Project(Namespace)
To deploy the project run the following command inside of the project where you would like to have the https://github.com/aerogear/mobile-security-service[Mobile Security Service] installed and running.

[source,shell]
----
$ oc project <my-project>
$ kubectl apply -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
----

=== To remove Mobile Security Service from the Project(Namespace)

The following command will remove all configuration made by the operator in the project/namespace.

[source,shell]
----
$ oc project <my-project>
$ kubectl delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
----

=== To remove Mobile Security Service Operator from your cluster.

The following commands will clean your cluster and remove all objects created for this operator.

[source,shell]
----
$ kubectl delete namespace mobile-security-service
$ kubectl delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml
$ kubectl delete -f deploy/cluster_role.yaml
$ kubectl delete -f deploy/cluster_role_binding.yaml
$ kubectl delete -f deploy/service_account.yaml
$ kubectl delete -f deploy/operator.yaml
----

=== Mobile Security Service Configurations

The environment variables used in this project are configured by the Config Map which is created by the operator in the project where its is installed.
To have a further understatement over its configuration see https://github.com/aerogear/mobile-security-service#setup-and-configurations[Setup and Configurations] section of https://github.com/aerogear/mobile-security-service[Mobile Security Service].

=== Creating Role for no-privilege users (TODO/Check)

[source,shell]
----
oc create \
  rolebinding developer-mobile-security-service-operator \
  --role=mobile-security-service-operator \
  --user=developer
----

== Contributing

All contributions are hugely appreciated. Please see our https://aerogear.org/community/#guides[Contributing Guide] for guidelines on how to open issues and pull requests. Please check out our link:./.github/CODE_OF_CONDUCT.md[Code of Conduct] too.

== Questions

There are a number of ways you can get in in touch with us, please see the https://aerogear.org/community/#contact[AeroGear community].
