ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]


:toc:
:toc-placement!:

= Mobile Security Service Operator

ifdef::status[]
.*Project health*
image:https://img.shields.io/:license-Apache2-blue.svg[License (License), link=http://www.apache.org/licenses/LICENSE-2.0]
image:https://goreportcard.com/badge/github.com/aerogear/mobile-security-service-operator[Go Report Card (Go Report Card), link=https://goreportcard.com/report/github.com/aerogear/mobile-security-service-operator]
endif::[]

:toc:
toc::[]

== Overview

A https://commons.openshift.org/sig/OpenshiftOperators.html[Operator] based on the https://github.com/operator-framework/operator-sdk[Operator SDK] to manage, install, configure the https://github.com/aerogear/mobile-security-service[Mobile Security Service] on a OpenShift/Kubernetes cluster.

== Prerequisites

|===
|https://golang.org/doc/install[Install Golang]
|https://github.com/golang/go/wiki/SettingGOPATH[Ensure the $GOPATH environment variable is set]
|https://golang.github.io/dep/docs/installation.html[Install the dep package manager]
|https://github.com/operator-framework/operator-sdk#quick-start[Install Operator-SDK]
|https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl[Install kubectl]
|===

== Getting Started

=== Getting the project

By the following commands you will create a local directory and clone this project.

[source,shell]
----
$ mkdir -p $GOPATH/src/github.com/aerogear/mobile-security-service-operator
$ cd $GOPATH/src/github.com/aerogear/mobile-security-service-operator
$ git clone https://github.com/aerogear/mobile-security-service-operator.git
$ cd $GOPATH/src/github.com/aerogear/mobile-security-service-operator
----

=== Installing on Minishift

https://docs.okd.io/latest/minishift/getting-started/installing.html[Install Minishift] then enable Operators on it by running the following commands.

[source,shell]
----
# create a new profile to test the operator
$ minishift profile set operator

# enable the admin-user add-on
$ minishift addon enable admin-user

# start the instance
$ minishift start
----

=== Configuring the Operator

Update the "mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml" with your cluster info. Following the place.

[source,yaml]
----
  # NOTE:
  # - Replace "{{clusterHost}}" for your cluster HOST. E.g 192.168.64.9
  # - You can use "$ oc status | grep server" or "kubectl cluster-info" to get this cluster info
  clusterHost: "{{clusterHost}}"
  hostSufix: ".nip.io"
----

=== Installing the Operator, Service and Roles on the cluster

Use the following command.

[source,shell]
----
$ make create-all
----

WARING: To create all you need be logged as admin. Use `oc login -u system:admin`.

=== Removing the Operator, Service and Roles on the cluster

Use the following command.

[source,shell]
----
$ make delete-all
----

IMPORTANT: To delete you need be logged as admin. (`oc login -u system:admin`)

== Configurations and Options

=== Environment Variables

The environment variables are used to configure the https://github.com/aerogear/mobile-security-service[Mobile Security Service] Application and Database. For a further understatement over its configuration see https://github.com/aerogear/mobile-security-service#setup-and-configurations[Setup and Configurations] section in https://github.com/aerogear/mobile-security-service[Mobile Security Service] README.

NOTE: All values used in the default configuration came from the config-map which is managed and created by the Operator.

=== Watch specifications for the MobileSecurityServiceBind (CR)

The Bind watches the applications in the cluster in order to create, delete and update the data in the https://github.com/aerogear/mobile-security-service[Mobile Security Service] by it REST API. It is the CR responsible for "bind/unbind/re-bind" the applications to the Service and by it CR properties which follows you will be able to define what applications should be watched/checked by this operator. For a further understanding check the link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicebind_cr.yaml[mobile-security-service_v1alpha1_mobilesecurityservicebind_cr.yaml] file.

=== Role for no-privilege users are able to create the Mobile Security Service App and Database

By executing the following commands you will create roles in the cluster which will allow the <user> create the Mobile Security Service Application and Database in their namespaces. In this would not be required be the system:admin. However, the Mobile Security Service Operator is cluster scoped and will still only accessible for the system admin users. (E.g `oc login -u system:admin`)

[source,shell]
----
$ oc create rolebinding developer-mobile-security-service-operator --role=mobile-security-service-operator --user=<user>
$ oc create rolebinding developer-mobile-security-service --role=mobile-security-service --user=<user>
----

== Local development

== To publish an new version of this operator

Following the steps.

=== Updating the operator tag version

* Replace the tag of the image in the `deploy/operator.yaml` file.

[source,yaml]
----
  # Replace this with the built image name
  image: aerogear/mobile-security-service-operator:0.1.0
----

NOTE: In this example the tag `0.1.0` will be replaced for the new one.

* Replace the tag in the `Makefile` file.

[source,shell]
----
TAG= 0.1.0
----

NOTE: In this example the tag `0.1.0` will be replaced for the new one.

IMPORTANT: Follow the https://semver.org/[Semantic Versioning] to define the new tags

=== Building and publish a new version tag in docker.hub

Run the following commands

[source,shell]
----
$ make build
$ make publish
----

=== To build and publish a development tag

[source,shell]
----
$ make build-dev
$ make publish-dev
----

=== To use locally the image from development tag

Update the image tag in the file `/mobile-security-service-operator/deploy/operator.yaml` with the development tag as follows.

[source,yaml]
----
# Replace this with the built image name
image: aerogear/mobile-security-service-operator:0.1.0-dev
----

== Using make commands

|===
| *Command*                     | *Description*
| `make create-all`             | Create mobile-security-service-operator namespace, operator, service and roles`
| `make delete-all`             | Delete mobile-security-service-operator namespace, operator, service and roles`
| `make create-oper`            | Create mobile-security-service namespace, operator and roles`
| `make delete-oper`            | Delete mobile-security-service namespace, operator and roles`
| `make create-olm`             | Create mobile-security-service namespace, catalogue operator(olm) and roles`
| `make delete-olm`             | Delete mobile-security-service namespace, catalogue operator(olm) and roles`
| `make create-app`             | Create Mobile Security Service App and its database in the project`
| `make create-app-only`        | Create Mobile Security Service App without its database`
| `make delete-app`             | Delete Mobile Security Service App and its database`
| `make delete-app-only`        | Delete Mobile Security Service App only`
| `make create-db-only`         | Create Mobile Security Service Database without its application`
| `make delete-db-only`         | Delete Mobile Security Service Database only`
| `make create-bind`            | Create Mobile Security Service Bind`
| `make delete-bind`            | Delete Mobile Security Service Bind`
| `make build`                  | Build operator with its tag`
| `make publish`                | Publish operator in https://hub.docker.com/[Docker Hub] with its tag`
| `make build-dev`              | Build operator for development proposes`
| `make publish-dev`            | Publish operator in https://hub.docker.com/[Docker Hub] for development proposes`
| `make vet`                    | Examines source code and reports suspicious constructs using https://golang.org/cmd/vet/[vet]
| `make fmt`                    | Formats code using https://golang.org/cmd/gofmt/[gofmt]
|===

NOTE: The link:./Makefile[Makefile] is implemented with tasks which you should use to work with.

== Supportability

This operator was developed using the k8s APIs and should work well in Kubernetes and OpenShift clusters.

== Contributing

All contributions are hugely appreciated. Please see our https://aerogear.org/community/#guides[Contributing Guide] for guidelines on how to open issues and pull requests. Please check out our link:./.github/CODE_OF_CONDUCT.md[Code of Conduct] too.

== Questions

There are a number of ways you can get in in touch with us, please see the https://aerogear.org/community/#contact[AeroGear community].
