ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]


:toc:
:toc-placement!:

= Mobile Security Service Operator

ifdef::status[]
.*Project health*
image:https://img.shields.io/:license-Apache2-blue.svg[License (License), link=http://www.apache.org/licenses/LICENSE-2.0]
image:https://goreportcard.com/badge/github.com/aerogear/mobile-security-service-operator[Go Report Card (Go Report Card), link=https://goreportcard.com/report/github.com/aerogear/mobile-security-service-operator]
endif::[]

:toc:
toc::[]

== Overview

A https://commons.openshift.org/sig/OpenshiftOperators.html[Operator] based on the https://github.com/operator-framework/operator-sdk[Operator SDK] that installs and maintains https://github.com/aerogear/mobile-security-service[AeroGear Mobile Security Service] on a cluster.

NOTE: This project is a POC

== Prerequisites

|===
|https://golang.org/doc/install[Install Golang]
|https://github.com/golang/go/wiki/SettingGOPATH[Ensure the $GOPATH environment variable is set]
|https://golang.github.io/dep/docs/installation.html[Install the dep package manager]
|https://github.com/operator-framework/operator-sdk#quick-start[Install Operator-SDK]
|===

== Getting Started

=== To run on Minishift
https://docs.okd.io/latest/minishift/getting-started/installing.html[Install Minishift] then enable Operators on it by running the following commands.

[source,shell]
----
# create a new profile to test the operator
$ minishift profile set operator

# enable the admin-user add-on
$ minishift addon enable admin-user

# start the instance
$ minishift start
----

=== To install Mobile Security Service Operator in cluster

==== Login as system:admin

To install the operator is required have admin permissions in the cluster.

[source,shell]
----
$ oc login -u system:admin
----

NOTE: This operator will be installed in the cluster level.

==== To config Mobile Security Service Operator
Update the "mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml" with your cluster info. Following the place.

[source,yaml]
----
  # NOTE:
  # - Replace "{{clusterHost}}" for your cluster HOST. E.g 192.168.64.9
  # - You can use "$ oc status | grep server" or "kubectl cluster-info" to get this cluster info
  clusterHost: "{{clusterHost}}"
  hostSufix: ".nip.io"
----

==== To deploy Mobile Security Service Operator

Use the following command.

[source,shell]
----
$ make deploy
----

NOTE: Following commands which will be executed with the `make deploy` to deploy the operator in your cluster.

[source,shell]
----
$ oc create namespace mobile-security-service-operator
$ oc create -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml
$ oc create -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_crd.yaml
$ oc create -f deploy/cluster_role.yaml
$ oc create -f deploy/cluster_role_binding.yaml
$ oc create -f deploy/service_account.yaml
$ oc create -f deploy/operator.yaml
----

TIP: You can use `kubectl` tool instead of `oc`. E.g. (`$ kubectl create namespace mobile-security-service`)

=== To deploy Mobile Security Service in a Project(Namespace) with its database

Use the following command.

[source,shell]
----
$ oc project <my-project>
$ make deploy-app
----

NOTE: Following the commands which will be executed with the `make deploy-app` to deploy the Mobile Security Service and its database in your project.

[source,shell]
----
$ oc apply -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
$ oc apply -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
----

=== To remove Mobile Security Service from the Project(Namespace) and its database

The following command will remove all configuration made by the operator in the project/namespace.

[source,shell]
----
$ oc project <my-project>
$ make undeploy-app
----

NOTE: Following the commands which will be executed with the `make undeploy-app` to undeploy the Mobile Security Service and its database from your project.

[source,shell]
----
$ oc delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
$ oc delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
----

=== To remove Mobile Security Service Operator from your cluster

Use the following command.

[source,shell]
----
$ make undeploy
----

NOTE: Following commands which will be executed with the `make undeploy` to undeploy the operator from your cluster.

[source,shell]
----
$ oc delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml
$ oc delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_crd.yaml
$ oc delete -f deploy/cluster_role.yaml
$ oc delete -f deploy/cluster_role_binding.yaml
$ oc delete -f deploy/service_account.yaml
$ oc delete -f deploy/operator.yaml
$ oc delete namespace mobile-security-service-operator
----

=== To deploy Mobile Security Service project without the database

Note that this operator has one type for the project and another for its database. In this way, its possible deploy them separately.

Use the following command to deploy just the Mobile Security Service in your project

[source,shell]
----
$ make deploy-app-only
----

NOTE: Following the command which will be executed with the `make deploy-app-only` to deploy the Mobile Security Service into your project.

[source,shell]
----
$ oc create -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
----

== Mobile Security Service Configurations

The environment variables used in this project are configured by the Config Map which is created by the operator. To have a further understatement over its configuration see https://github.com/aerogear/mobile-security-service#setup-and-configurations[Setup and Configurations] section of https://github.com/aerogear/mobile-security-service[Mobile Security Service].

TIP: For example, see that the name of the database is mapped in the ConfigMap which is used by Mobile Security Service application and database. Note that to connect to the database with the default values you may use the command: `psql -h localhost -U postgresql mobile_security_service.

== Creating Role for no-privilege users (TODO/Check)

[source,shell]
----
oc create \
  rolebinding developer-mobile-security-service-operator \
  --role=mobile-security-service-operator \
  --user=developer
----

== Using make commands

|===
| *Command*                     | *Description*
| `make deploy`                 | Create mobile-security-service namespace and deploy operator and roles`
| `make undeploy`               | Remove mobile-security-service namespace and undeploy operator and roles`
| `make deploy-app`             | Deploy Mobile Security Service and its database in the project`
| `make deploy-app-only`        | Deploy Mobile Security Service without its database in the project`
| `make undeploy-app`           | Undeploy Mobile Security Service e and its database in from the project`
| `make build`                  | Build operator for development proposes`
| `make publish`                | Publish operator in https://hub.docker.com/[Docker Hub]`
| `make vet`                    | Examines source code and reports suspicious constructs using https://golang.org/cmd/vet/[vet]
| `make fmt`                    | Formats code using https://golang.org/cmd/gofmt/[gofmt]
|===

NOTE: The link:./Makefile[Makefile] is implemented with tasks which you should use to work with.

== Contributing

All contributions are hugely appreciated. Please see our https://aerogear.org/community/#guides[Contributing Guide] for guidelines on how to open issues and pull requests. Please check out our link:./.github/CODE_OF_CONDUCT.md[Code of Conduct] too.

== Questions

There are a number of ways you can get in in touch with us, please see the https://aerogear.org/community/#contact[AeroGear community].
