ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]


:toc:
:toc-placement!:

= Mobile Security Service Operator

ifdef::status[]
.*Project health*
image:https://img.shields.io/:license-Apache2-blue.svg[License (License), link=http://www.apache.org/licenses/LICENSE-2.0]
image:https://goreportcard.com/badge/github.com/aerogear/mobile-security-service-operator[Go Report Card (Go Report Card), link=https://goreportcard.com/report/github.com/aerogear/mobile-security-service-operator]
endif::[]

:toc:
toc::[]

== Overview

A https://commons.openshift.org/sig/OpenshiftOperators.html[Operator] based on the https://github.com/operator-framework/operator-sdk[Operator SDK] that installs and maintains https://github.com/aerogear/mobile-security-service[AeroGear Mobile Security Service] on a cluster.

NOTE: This project is a POC

== Prerequisites

|===
|https://golang.org/doc/install[Install Golang]
|https://github.com/golang/go/wiki/SettingGOPATH[Ensure the $GOPATH environment variable is set]
|https://golang.github.io/dep/docs/installation.html[Install the dep package manager]
|https://github.com/operator-framework/operator-sdk#quick-start[Install Operator-SDK]
|https://kubernetes.io/docs/tasks/tools/install-kubectl/#install-kubectl[Install kubectl]
|===

== Getting Started

=== Getting the project

[source,shell]
----
$ mkdir -p $GOPATH/src/github.com/aerogear/mobile-security-service-operator
$ cd $GOPATH/src/github.com/aerogear/mobile-security-service-operator
$ git clone https://github.com/aerogear/mobile-security-service-operator.git
$ cd $GOPATH/src/github.com/aerogear/mobile-security-service-operator
----

=== To run on Minishift
https://docs.okd.io/latest/minishift/getting-started/installing.html[Install Minishift] then enable Operators on it by running the following commands.

[source,shell]
----
# create a new profile to test the operator
$ minishift profile set operator

# enable the admin-user add-on
$ minishift addon enable admin-user

# start the instance
$ minishift start
----

=== To install the Operator and Service

Use the following command.

[source,shell]
----
$ make deploy-all
----

IMPORTANT: To install the Operator and Service you need be logged as admin since they will be in the cluster level.

=== To uninstall the Operator and Service

Use the following command.

[source,shell]
----
$ make undeploy-all
----

== More options to install

=== To install Mobile Security Service Operator in cluster

==== Login as system:admin

To install the operator is required have admin permissions in the cluster.

[source,shell]
----
$ oc login -u system:admin
----

NOTE: This operator will be installed in the cluster level.

==== To config Mobile Security Service Operator
Update the "mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml" with your cluster info. Following the place.

[source,yaml]
----
  # NOTE:
  # - Replace "{{clusterHost}}" for your cluster HOST. E.g 192.168.64.9
  # - You can use "$ oc status | grep server" or "kubectl cluster-info" to get this cluster info
  clusterHost: "{{clusterHost}}"
  hostSufix: ".nip.io"
----

==== To deploy ONLY Mobile Security Service Operator

Use the following command.

[source,shell]
----
$ make deploy
----

NOTE: Following commands which will be executed with the `make deploy` to deploy the operator in your cluster.

[source,shell]
----
$ kubectl create namespace mobile-security-service-operator
$ kubectl create -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml
$ kubectl create -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_crd.yaml
$ kubectl create -f deploy/cluster_role.yaml
$ kubectl create -f deploy/cluster_role_binding.yaml
$ kubectl create -f deploy/service_account.yaml
$ kubectl create -f deploy/operator.yaml
----

TIP: You can use `oc` tool instead of `kubectl`. E.g. (`$ oc create namespace mobile-security-service`)

=== To deploy ONLY Mobile Security Service with its database

Use the following command.

[source,shell]
----
$ make deploy-app
----

NOTE: Following the commands which will be executed with the `make deploy-app` to deploy the Mobile Security Service and its database in your project.

[source,shell]
----
$ kubectl apply -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
$ kubectl apply -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
----

=== To remove ONLY Mobile Security Service from and its database

Use the following command.

[source,shell]
----
$ make undeploy-app
----

NOTE: Following the commands which will be executed with the `make undeploy-app` to undeploy the Mobile Security Service and its database from your project.

[source,shell]
----
$ kubectl delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
$ kubectl delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
----

=== To remove ONLY Mobile Security Service Operator from your cluster

Use the following command.

[source,shell]
----
$ make undeploy
----

NOTE: Following commands which will be executed with the `make undeploy` to undeploy the operator from your cluster.

[source,shell]
----
$ kubectl delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_crd.yaml
$ kubectl delete -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_crd.yaml
$ kubectl delete -f deploy/cluster_role.yaml
$ kubectl delete -f deploy/cluster_role_binding.yaml
$ kubectl delete -f deploy/service_account.yaml
$ kubectl delete -f deploy/operator.yaml
$ kubectl delete namespace mobile-security-service-operator
----

=== To deploy Mobile Security Service App without the database

Note that this operator has one type for the project and another for its database. In this way, its possible deploy them separately.

Use the following command to deploy only the Mobile Security Service App.

[source,shell]
----
$ make deploy-app-only
----

NOTE: Following the command which will be executed with the `make deploy-app-only` to deploy the Mobile Security Service App.

[source,shell]
----
$ oc create -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml
----

NOTE: Also, you can use `make undeploy-app-only`

=== To deploy ONLY Mobile Security Service Database

Use the following command to deploy only the Mobile Security Service Database.

[source,shell]
----
$ make deploy-db-only
----

NOTE: Following the command which will be executed with the `make deploy-db-only` to deploy the Mobile Security Service DB.

[source,shell]
----
$ oc create -f deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml
----

NOTE: Also, you can use `make undeploy-db-only`

== To publish an new version of this operator

Following the steps.

=== Updating the operator tag version

* Replace the tag of the image in the `deploy/operator.yaml` file.

[source,yaml]
----
  # Replace this with the built image name
  image: aerogear/mobile-security-service-operator:0.1.0
----

NOTE: In this example the tag `0.1.0` will be replaced for the new one.

* Replace the tag in the `Makefile` file.

[source,shell]
----
TAG= 0.1.0
----

NOTE: In this example the tag `0.1.0` will be replaced for the new one.

IMPORTANT: Follow the https://semver.org/[Semantic Versioning] to define the new tags

=== Building and pushing the new version

Run the following commands

[source,shell]
----
$ make build
$ make publish
----

== Mobile Security Service Application and Database configurations

The environment variables used in this project are configured by the Config Map which is created by the operator. To have a further understatement over its configuration see https://github.com/aerogear/mobile-security-service#setup-and-configurations[Setup and Configurations] section of https://github.com/aerogear/mobile-security-service[Mobile Security Service].

TIP: For example, see that the name of the database is mapped in the ConfigMap which is used by Mobile Security Service application and database. Note that to connect to the database with the default values you may use the command: `psql -h localhost -U postgresql mobile_security_service.

== Creating Role for no-privilege users are able to create the application and database in their namespaces

By executing the following commands you will create roles in the cluster which will allow the <user> create the Mobile Security Service Application and Database in their namespaces. However, the Mobile Security Service Operator is cluster scoped and will still only accessible for the system admin users. (E.g `oc login -u system:admin`)

[source,shell]
----
$ oc create rolebinding developer-mobile-security-service-operator --role=mobile-security-service-operator --user=<user>
$ oc create rolebinding developer-mobile-security-service --role=mobile-security-service --user=developer
----

== Local development

=== To build and publish a development tag

[source,shell]
----
$ make build-dev
$ make publish-dev
----

=== To use locally the development tag

Update the image tag in the file `/mobile-security-service-operator/deploy/operator.yaml` with the development tag as follows.

[source,yaml]
----
# Replace this with the built image name
image: aerogear/mobile-security-service-operator:0.1.0-dev
----

== Using make commands

|===
| *Command*                     | *Description*
| `make deploy-all`             | Create mobile-security-service-operator namespace and deploy operator, roles and Service`
| `make undeploy-all`           | Delete mobile-security-service-operator namespace and undeploy operator, roles and Service`
| `make undeploy`               | Remove mobile-security-service namespace and undeploy operator and roles`
| `make deploy`                 | Create mobile-security-service namespace and deploy operator and roles`
| `make undeploy`               | Remove mobile-security-service namespace and undeploy operator and roles`
| `make deploy-app`             | Deploy Mobile Security Service and its database in the project`
| `make deploy-app-only`        | Deploy Mobile Security Service without its database in the project`
| `make undeploy-app`           | Undeploy Mobile Security Service e and its database in from the project`
| `make build`                  | Build operator`
| `make publish`                | Publish operator in https://hub.docker.com/[Docker Hub]`
| `make build-dev`              | Build operator for development proposes`
| `make publish-dev`            | Publish operator in https://hub.docker.com/[Docker Hub] for development proposes`
| `make vet`                    | Examines source code and reports suspicious constructs using https://golang.org/cmd/vet/[vet]
| `make fmt`                    | Formats code using https://golang.org/cmd/gofmt/[gofmt]
|===

NOTE: The link:./Makefile[Makefile] is implemented with tasks which you should use to work with.

== Supportability

This operator was developed using the k8s APIs and should work well in Kubernetes and OpenShift clusters.

== Contributing

All contributions are hugely appreciated. Please see our https://aerogear.org/community/#guides[Contributing Guide] for guidelines on how to open issues and pull requests. Please check out our link:./.github/CODE_OF_CONDUCT.md[Code of Conduct] too.

== Questions

There are a number of ways you can get in in touch with us, please see the https://aerogear.org/community/#contact[AeroGear community].
