# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/aerogear/mobile-security-service-operator

    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout
      - run:
          name: Install dep
          command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make setup
      - run: make test
      - run: make build_linux

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/