# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    working_directory: /go/src/github.com/aerogear/mobile-security-service-operator

    docker:
      - image: circleci/golang:1.10

    steps:
      - checkout
      - run:
          name: Install dep
          command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: make setup
      - run: make test
      - run: make build_linux

  docker_push_master:
    working_directory: /go/src/github.com/aerogear/mobile-security-service-operator
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: 
        name: Install dep
        command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
        name: Install operator-sdk to build image
        command: curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.5.0/operator-sdk-v0.5.0-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin/
      - run: make setup
      # circle ci key required for docker builds
      - setup_remote_docker
      - run: make build-linux 
      - run: make build-master
      - run: make push-master

  docker_release:
    working_directory: /go/src/github.com/aerogear/mobile-security-service-operator
    docker:
      - image: circleci/golang:1.10
    steps:
      - checkout
      - run: 
        name: Install dep
        command: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
        name: Install operator-sdk to build image
        command: curl -Lo operator-sdk https://github.com/operator-framework/operator-sdk/releases/download/v0.6.0/operator-sdk-v0.6.0-x86_64-linux-gnu && chmod +x operator-sdk && sudo mv operator-sdk /usr/local/bin/
      - run: make setup
      - run: 
        name: Install goreleaser
        command: curl -sL https://raw.githubusercontent.com/goreleaser/get/master/get | bash
      # circle ci key required for docker builds
      - setup_remote_docker
      - run: make build-release
      - run: make push-release
      - store_artifacts:
          path: dist

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - docker_push_master:
          requires:
            - build
          filters:
            branches:
              only:
                - master
      - docker_release:
          requires:
            - build
          filters:
            tags:
              only: /\d{1,2}\.\d{1,2}\.\d{1,2}/
            branches:
              ignore: /.*/