apiVersion: mobile-security-service.aerogear.com/v1alpha1
kind: MobileSecurityServiceDB
metadata:
  name: mobile-security-service-db
spec:
  size: 1
  image: "postgres:9.6"
  containerName: "database"
  databaseName: "mobile_security_service"
  databasePassword: "postgres"
  databaseUser: "postgresql"
  databasePort: 5432
  databaseMemoryLimit: "512Mi"
  databaseMemoryRequest: "512Mi"
  databaseStorageRequest: "1Gi"
  configMapName: "mobile-security-service-app"