# This CR defines the specs of the PostgreSQL Database which will be installed/managed by the Operator
apiVersion: mobile-security-service.aerogear.com/v1alpha1
kind: MobileSecurityServiceDB
metadata:
  name: mobile-security-service-db
spec:

  # NOTE: If no specs be defined here the constants values in the code implementation will be applied

  # ---------------------------------
  # DB Resources
  # ---------------------------------

  size: 1

  # ---------------------------------
  # Database Container
  # ---------------------------------

  # The imaged used in this project is from Red Hat. See more in https://docs.okd.io/latest/using_images/db_images/postgresql.html
  image: "centos/postgresql-96-centos7"
  containerName: "database"
  # Use the following spec if you would like to define the image policy
  # containerImagePullPolicy: "IfNotPresent"

  # Following are the values which will be used as the key label for the environment variable of the database image.
  databaseNameParam: "POSTGRESQL_DATABASE"
  databasePasswordParam: "POSTGRESQL_PASSWORD"
  databaseUserParam: "POSTGRESQL_USER"

  databasePort: 5432
  databaseMemoryLimit: "512Mi"
  databaseMemoryRequest: "512Mi"
  databaseStorageRequest: "1Gi"

  # ---------------------------------
  # Environment Variables
  # ---------------------------------

  # IMPORTANT: By default the database will use the values defined in the Mobile Security Service and shared via a Config Map.
  # The following specs are just used just if the database be installed without the Service (standalone)
  databaseName: "mobile_security_service"
  databasePassword: "postgres"
  databaseUser: "postgresql"
