apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mobile-security-service-operator
  namespace: mobile-security-service-operator
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  - serviceaccounts
  - rolebindings
  - routes
  - oauthclients
  verbs:
  - "*"
- apiGroups:
  - oauth.openshift.io
  resources:
  - oauthclients
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - mobile-security-service-operator
  - mobile-security-service-db
  - mobile-security-service
  - mobile-security-service-app
  - mobile-security-service-unbind
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - mobile-security-service.aerogear.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - "*"