apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-security-service-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mobile-security-service-operator
  template:
    metadata:
      labels:
        name: mobile-security-service-operator
    spec:
      serviceAccountName: mobile-security-service-operator
      containers:
        - name: mobile-security-service-operator
          # Replace this with the built image name
          image: docker.io/cmacedo/mobile-security-service-operator:SDK-CONFIG
          command:
          - mobile-security-service-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APP_NAMESPACES
              # Replace this with the valid namespaces to allow apply the MobileSecurityServiceApp
              value: "mobile-security-service-apps"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mobile-security-service-operator"



