apiVersion: v1
kind: Service
metadata:
  labels:
    name: mobile-security-service-operator
  name: mobile-security-service-operator
  namespace: mobile-security-service
  resourceVersion: '66190'
  selfLink: >-
    /api/v1/namespaces/mobile-security-service/services/mobile-security-service-operator
spec:
  ports:
    - name: metrics
      port: 8383
      protocol: TCP
      targetPort: 8383
  selector:
    name: mobile-security-service-operator
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}