kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mobile-security-service-operator
  namespace: mobile-security-service
subjects:
- kind: ServiceAccount
  name: mobile-security-service-operator
  # Replace this with the namespace the operator is deployed in.
  namespace: mobile-security-service
roleRef:
  kind: ClusterRole
  name: mobile-security-service-operator
  apiGroup: rbac.authorization.k8s.io
