apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mobile-security-service
rules:
- apiGroups:
  - "mobile-security-service.aerogear.com"
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - mobile-security-service-app
  - mobile-security-service-db
  verbs:
  - "*"
