kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mobile-security-service-bind
subjects:
- kind: ServiceAccount
  name: mobile-security-service-bind
roleRef:
  kind: Role
  name: mobile-security-service-bind
  apiGroup: rbac.authorization.k8s.io
