kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mobile-security-service
subjects:
- kind: ServiceAccount
  name: mobile-security-service
roleRef:
  kind: Role
  name: mobile-security-service
  apiGroup: rbac.authorization.k8s.io
