kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mobile-security-service-operator
subjects:
- kind: ServiceAccount
  name: mobile-security-service-operator
  # Replace this with the namespace where the operator will be deployed.
  namespace: mobile-security-service
roleRef:
  kind: ClusterRole
  name: mobile-security-service-operator
  apiGroup: rbac.authorization.k8s.io
