{
 "title": "Mobile Security Service Operator",
 "description": "Application metrics",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Daily Percentage Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "((sum(avg_over_time(up{job='mobile-security-service-operator'}[1m])))/(count(avg_over_time(up{job='mobile-security-service-operator'}[30m]))))*100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "up{job='mobile-security-service-operator'}",
     "legendFormat": "{{service}} - Uptime"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job='mobile-security-service-operator'}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job='mobile-security-service-operator'}",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{container='mobile-security-service-operator'}",
     "legendFormat": "Max Memory Allocation"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job='mobile-security-service-operator'}[1m]))*1000",
     "legendFormat": "Mobile Security Service Operator- CPU Usage in Millicores"
    },
    {
     "expr": "(kube_pod_container_resource_limits_cpu_cores{container='mobile-security-service-operator'})*1000",
     "legendFormat": "Maximum Limit of Millicores"
    }
   ]
  }
 ]
}