{
 "title": "Mobile Security Service Application",
 "description": "Application metrics",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Uptime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Admin Console Average Percentage Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kube_endpoint_address_available{endpoint='mobile-security-service-application'})*100"
    }
   ]
  },
  {
   "title": "Admin Console - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 1 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kube_endpoint_address_available{endpoint='mobile-security-service-application'}",
     "legendFormat": "Admin Console - Uptime"
    }
   ]
  },
  {
   "title": "Database Average Percentage - Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_running{namespace='mobile-security-service',container='database'})*100"
    }
   ]
  },
  {
   "title": "Mobile Security Service Application Database - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_pod_container_status_running{namespace='mobile-security-service',container='database'}",
     "legendFormat": "Postgres Database - Uptime"
    }
   ]
  },
  {
   "title": "MSS Application Average Percentage Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 17 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(up{job=\"mobile-security-service-application\"})*100"
    }
   ]
  },
  {
   "title": "Mobile Security Service Application - Uptime",
   "type": "graph",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{job='mobile-security-service-application'}",
     "legendFormat": "Mobile Security Service Applition - Uptime"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{job='mobile-security-service-operator'}",
     "legendFormat": "Virtual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{job='mobile-security-service-operator'}",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "kube_pod_container_resource_limits_memory_bytes{container='mobile-security-service-operator'}",
     "legendFormat": "Max Memory Allocation"
    },
    {
     "expr": "((kube_pod_container_resource_limits_memory_bytes{container='mobile-security-service-operator'})/100)*90",
     "legendFormat": "90% of Max Memory Allocation"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short", "label": "Millicores" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{job='mobile-security-service-operator'}[1m]))*1000",
     "legendFormat": "Mobile Security Service Application - CPU Usage in Millicores"
    },
    {
     "expr": "(kube_pod_container_resource_limits_cpu_cores{container='mobile-security-service-operator'})*1000",
     "legendFormat": "Maximum Limit of Millicores"
    },
    {
     "expr": "(((kube_pod_container_resource_limits_cpu_cores{container='mobile-security-service-operator'})*1000)/100)*90",
     "legendFormat": "90% Limit of Millicores"
    }
   ]
  },
  { "title": "API HTTP Monitoring", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "API Requests Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(api_requests_duration_seconds{job=\"mobile-security-service-application\"})",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Rate of HTTP Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Rate of HTTP Errors/Second" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests_failure_total[30m])",
     "legendFormat": "Errors {{code}} - {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Rate of  HTTP Responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short", "label": "Rate of HTTP Responses/Second" }
   ],
   "targets": [
    {
     "expr": "rate(api_requests_total[1h])",
     "legendFormat": "{{method}} - {{code}} - {{path}}"
    }
   ]
  },
  {
   "title": "Max API Requests Duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 52 },
   "format": "s",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(api_requests_duration_seconds{job='mobile-security-service-application'})"
    }
   ]
  },
  {
   "title": "Minium API Requests Duration Seconds",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 52 },
   "format": "s",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(api_requests_duration_seconds{job='mobile-security-service-application'})"
    }
   ]
  },
  {
   "title": "Average API Requests Duration",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 56 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(api_requests_duration_seconds{job='mobile-security-service-application'})"
    }
   ]
  },
  {
   "title": "Average API requests in flight",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 56 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(api_requests_in_flight{job='mobile-security-service-application'})"
    }
   ]
  }
 ]
}