# Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring-key: middleware
  name: mobile-security-service
spec:
  endpoints:
    - path: /api/metrics
      port: server
  selector:
    matchLabels:
      app: mobile-security-service