# Monitor Service (Metrics) for integr8ly
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    monitoring-key: middleware
  name: mobile-security-service
spec:
  endpoints:
    - path: /metrics
      port: metrics
  selector:
    matchLabels:
      name: mobile-security-service-operator