ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]

:toc:
:toc-placement!:

= Mobile Security Service - Standard Operating Procedures

:toc:
toc::[]

== Critical

=== MobileSecurityServiceConsoleDown or MobileSecurityServiceDown

. Check that the Mobile Security Service CR is deployed in the same namespace as the operator by running `oc get MobileSecurityService`
. Check the status of the Mobile Security Service CR by running `oc describe MobileSecurityService`
+
NOTE: Check that the status are as expected as described in the https://github.com/aerogear/mobile-security-service-operator#status-definition-per-types[Status Definitions per Types in the README]
+
. Check if the Mobile Security Service image was pulled successfully.
. Check the operator pod is present as it is responsible for managing the service pod as described in https://github.com/aerogear/mobile-security-service-operator/blob/0.2.0/SOP/SOP-operator.adoc[MobileSecurityServiceOperatorDown]

=== MobileSecurityServiceDatabaseDown

. Check that the Mobile Security Service DB CR is deployed in the same namespace as the operator by running `oc get MobileSecurityServiceDB`
. Check the status of the Mobile Security Service CR by running `oc describe MobileSecurityServiceDB`
+
NOTE: Check that the status are as expected as described in the https://github.com/aerogear/mobile-security-service-operator#status-definition-per-types[Status Definitions per Types in the README]
+
.. Run `oc get pods | grep mobile-security-service-db`
+
NOTE: By default it should use the values defined in the ConfigMap created by the operator `mobile-security-service-config`. For a further information see link:.https://github.com/aerogear/mobile-security-service-operator#changing-the-environment-variables-values[Changing the Environment Variables values in the README]
+
. Check the pod logs by running `oc logs <database-podname>`
+
NOTE: You can save the logs by running `oc logs <database-podname> > <filename>.log`
+
. Check the operator pod is present as it is responsible for managing the service pod as described in https://github.com/aerogear/mobile-security-service-operator/blob/0.2.0/SOP/SOP-operator.adoc[MobileSecurityServiceOperatorDown]

== Warning

=== MobileSecurityServicePodCPUHigh

. Please following the <<General procedure>> procedure before in order to capture the logs and send it to its maintainers.
. In order to solve following the steps to <<Scaling the pods>>.

=== MobileSecurityServicePodMemoryHigh

. Please following the <<General procedure>> procedure before in order to capture the logs and send it to its maintainers.
. In order to solve following the steps to <<Scaling the pods>>.

=== MobileSecurityServiceApiHighRequestDuration

. Please following the <<General procedure>> procedure before in order to capture the logs and send it to its maintainers.
. In order to solve following the steps to <<Scaling the pods>>.

=== MobileSecurityServiceApiHighRequestFailure

. Please following the <<General procedure>> procedure before in order to capture the logs and send it to its maintainers.

=== MobileSecurityServiceApiHighConcurrentRequests

. Please following the <<General procedure>> procedure before in order to capture the logs and send it to its maintainers.

== General procedure

The following steps would be performed by the Console (OCP UI)

. Capture a snapshot of the 'Mobile Security Service Application' Grafana dashboard and track it over time. The metrics can be useful for identifying performance issues over time.
. Increase the log level of the Service pod (`pod/mobile-security-service-<xyz123>`)
.. Go to `Applications -> Deployment` and click on in the `mobile-security-service`
.. Go to the `Environment` tab
.. Remove the `Env Var` `LOG_LEVEL` and add a new `Env Var` `LOG_LEVEL` with the value `debug`
.. After saving the re-deploy of the service will be done automatically then you will be able to get further information

The following steps which can be performed by CLI:

NOTE: You are able to the the logs by the Console (OCP UI) as well.

. Capture application logs for analysis.
.. Get the pod names by running `oc get pods`
.. Save the logs by running `oc logs <database-podname> > <filename>.log` for each pod

NOTE: If necessary, you can recreate the service pod to restore service oc delete pod <service-podname>`.

== Scaling the pods

You can scale the MSS pod by changing the spec size in the Mobile Security Service CR. See link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml[MobileSecurityService CR].

. Run `oc edit MobileSecurityService` and add the new spec size for it. Also, you can delete and re-apply the link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml[MobileSecurityService CR]

NOTE: The architecture of Mobile Security Service do not allow scale its database.




