ifdef::env-github[]
:status:
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:table-caption!:
endif::[]

:toc:
:toc-placement!:

= Mobile Security Service - Standard Operating Procedures

:toc:
toc::[]

== Overview

The following guide outlines the steps required to manage and solve issues over the https://github.com/aerogear/mobile-security-service[Mobile Security Service] managed, installed and configured via the https://github.com/aerogear/mobile-security-service-operator[Mobile Security Service Operator].

== Reference Articles

- https://github.com/aerogear/mobile-security-service/blob/master/README.adoc[Mobile Security Service]
- https://github.com/aerogear/mobile-security-service-operator/blob/master/README.adoc[Mobile Security Service Operator]
- https://prometheus.io/docs/practices/alerting/[Prometheus Alerts documentation]

== Success Indicators

All alerts need to be green in the `Prometheus Alert Monitoring`. 

== Prometheus Alerts Procedures

The following guide outlines the steps required to solve issues which will be alert by the Prometheus alerts configured to monitoring the https://github.com/aerogear/mobile-security-service[Mobile Security Service] when it is managed, installed and configured via the https://github.com/aerogear/mobile-security-service-operator[Mobile Security Service Operator].

IMPORTANT: Before check any following steps see if the operator pod is running successful. More info: https://github.com/aerogear/mobile-security-service-operator/blob/0.4.0/SOP/SOP-operator.adoc[MobileSecurityServiceOperatorDown]

TIP: By the CR status you are able to identify what is missing. Also, it is an important information to be send to its maintainers in the case you need their help with. See the status descriptions in the https://github.com/aerogear/mobile-security-service-operator#status-definition-per-types[Status Definitions per Types in the README]

TIP: You can save the logs by running `oc logs <podname> > <filename>.log`. The logs can provided to you useful information in order to identify the root cause of the issue as they are required information to be send to its maintainers in the case it need to be checked by them.

=== Critical

==== MobileSecurityServiceConsoleDown or MobileSecurityServiceDown

The pod which runs the https://github.com/aerogear/mobile-security-service[Mobile Security Service] is down or is not present in the same namespace of the operator.

. Check if the MobileSecurityService pod is present and running by running `oc get pods`. More info: link:https://github.com/aerogear/mobile-security-service-operator#Installing[Installing].
. Check if the Mobile Security Service image was pulled successfully. More info: link:https://github.com/aerogear/mobile-security-service-operator/README.adoc#publishing-images[Publishing Images].
. Check if the link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml[MobileSecurityService CR] is applied in the same namespace as the operator by running `oc get MobileSecurityService`.
+
NOTE: The link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml[MobileSecurityService CR] for the operator be able to create and manage the https://github.com/aerogear/mobile-security-service/blob/master/README.adoc[Mobile Security Service] pod/container.
+
. Check the status of the link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml[MobileSecurityService CR] by running `oc describe MobileSecurityService`
. Check the pod logs by running `oc logs <podname>`
+
WARNING: Check if the <<MobileSecurityServiceDatabaseDown>> was not triggered. See that the Service requires its Database in order to work successfully.

==== MobileSecurityServiceDatabaseDown

The pod which runs the https://github.com/aerogear/mobile-security-service[Mobile Security Service]'s Database(PostgreSQL) is down or is not present in the same namespace of the operator.

. Check that the link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml[MobileSecurityServiceDB CR] is deployed in the same namespace as the operator by running `oc get MobileSecurityServiceDB`. The link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml[MobileSecurityServiceDB CR] need to be applied in order to allow the operator be able to create/manage the Database pod.
. Check the status of the link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicedb_cr.yaml[MobileSecurityServiceDB CR] by running `oc describe MobileSecurityServiceDB`. See the status descriptions in the https://github.com/aerogear/mobile-security-service-operator#status-definition-per-types[Status Definitions per Types in the README]
. Check if the pod is running by `oc get pods | grep mobile-security-service-db`. See the link:.https://github.com/aerogear/mobile-security-service-operator#Installing[Installing section in the README] in order to have a better idea over the expected results.
+
WARING: By default it should use the values defined in the ConfigMap created by the operator `mobile-security-service-config`. For a further information see link:.https://github.com/aerogear/mobile-security-service-operator#changing-the-environment-variables-values[Changing the Environment Variables values in the README]
+
. Check the pod logs by running `oc logs <database-podname>`

=== Warning

==== MobileSecurityServicePodCPUHigh

It means that Service pod(s) are using more CPU than expected.

. Please following the <<To capture the logs>> procedure in order to capture the required information to send it to its maintainers.
. Following the steps <<To scale the pod>> in order to try to solve performance issues.

==== MobileSecurityServicePodMemoryHigh

It means that Service pod(s) are using more Memory than expected.

. Please following the <<To capture the logs>> procedure in order to capture the required information to send it to its maintainers.
. Following the steps <<To scale the pod>> in order to try to solve performance issues.

==== MobileSecurityServiceApiHighRequestDuration

It means that the requests performed to the MSS Service are taking too long.

. Please following the <<To capture the logs>> procedure in order to capture the required information to send it to its maintainers.
. Following the steps <<To scale the pod>> in order to try to solve performance issues.

==== MobileSecurityServiceApiHighRequestFailure

It means that are to many requests to the MSS Service falling.

. Please following the <<To capture the logs>> procedure before in order to capture the logs and send it to its maintainers.

TIP: May delete the MobileSecurityService Deployment could allow the operator re-create it with the correct configuration.

==== MobileSecurityServiceApiHighConcurrentRequests

It means that MSS API has HTTP requests latency longer that 30 seconds.

. Please following the <<To capture the logs>> procedure in order to capture the required information to send it to its maintainers.
. Following the steps <<To scale the pod>> in order to try to solve performance issues.

=== To capture the logs

The following steps would be performed by the Console (OCP UI)

. Capture a snapshot of the 'Mobile Security Service Application' Grafana dashboard and track it over time. The metrics can be useful for identifying performance issues over time.
. Increase the log level of the Service pod (`pod/mobile-security-service-<xyz123>`)
.. Go to `Applications -> Deployment` and click on in the `mobile-security-service`
.. Go to the `Environment` tab
.. Remove the `Env Var` `LOG_LEVEL` and add a new `Env Var` `LOG_LEVEL` with the value `debug`
.. After saving the re-deploy will be done automatically.

. Capture the Service logs
+
NOTE: You are able to capture the logs by the Console (OCP UI).
+
.. Get the pod names by running `oc get pods`
.. Save the logs by running `oc logs <database-podname> > <filename>.log` for each pod
. Capture CR Status by running `oc describe <CRDKind>`. See the https://github.com/aerogear/mobile-security-service-operator#crd-definitions[CRD Definitions] to know all kinds.
+
NOTE: The above steps may bring an useful information for you identify the root cause and they are important to capture the required data for its maintainers are able to do improvements and/or fixes to avoid this scenario.

=== To scale the pod

You can scale the MSS pod by changing the spec size in the link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservice_cr.yaml[MobileSecurityService CR].

. Run `oc edit MobileSecurityService` and add the new spec size for it.

IMPORTANT: The architecture of https://github.com/aerogear/mobile-security-service[Mobile Security Service] will not allow you scale its database.

== Validate

IMPORTANT: The `OK` status which has for all CR/CRD kinds means that all objects required and managed by its controller was created and managed successfully.

=== Installation

Following the steps to ensure that all is as expected.

. Switch to the Mobile Security Service namespace by running `oc project <namespace>`. E.g `oc project mobile-security-service`
. Check if the its Service and Database are installed with success by run `oc describe MobileSecurityService` and `oc describe MobileSecurityServiceDB` and checking with both has the `OK` status.

NOTE: You can check the https://github.com/aerogear/mobile-security-service-operator#Installing[Installing] in order to have a better idea over the expected result.

=== Optional configurations

==== Monitor

If the https://github.com/aerogear/mobile-security-service-operator/blob/master/README.adoc#monitoring-service-metrics[Monitoring Service (Metrics)] is enabled for your installation you are able to check its Grafana Dashboard, `Mobile Security Service Application`, and the Prometheus Monitoring instance used for it.

==== Backup

If the https://github.com/aerogear/mobile-security-service-operator#configuring-the-backup-service[Backup Service] is enable then you are able to check if the link:./deploy/crds/mobile-security-service_v1alpha1_mobilesecurityservicebackup_crd.yaml[MobileSecurityServiceBackup] are applied, installed and configured with success by running `oc describe MobileSecurityBackup`. See https://github.com/aerogear/mobile-security-service-operator#verifying[Verifying] section in the README.


