apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mobilesecurityservicebackups.mobile-security-service.aerogear.org
spec:
  group: mobile-security-service.aerogear.org
  names:
    kind: MobileSecurityServiceBackup
    listKind: MobileSecurityServiceBackupList
    plural: mobilesecurityservicebackups
    singular: mobilesecurityservicebackup
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            schedule:
              type: string
            image:
              type: string
            databaseVersion:
              type: string
            productName:
              type: string
            awsS3BucketName:
              type: string
            awsAccessKeyId:
              type: string
            awsSecretAccessKey:
              type: string
            awsCredentialsSecretName:
              type: string
            encryptionKeySecretName:
              type: string
            awsCredentialsSecretNamespace:
              type: string
            encryptionKeySecretNamespace:
              type: string
            gpgPublicKey:
              type: string
            gpgEmail:
              type: string
              format: email
            gpgTrustModel:
              type: string
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true

